package com.ilogic.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by gerry on 2017/2/28.
 */
    @Entity
    @Table(name = "users")
    public class User {

        // An autogenerated id (unique for each user in the db)
        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        private long id;

        @NotNull
        private String email;

        @NotNull
        private String name;

        // Public methods

        public User() { }

        public User(long id) {
            this.id = id;
        }

        public User(String email, String name) {
            this.email = email;
            this.name = name;
        }

    public long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getName() {
        return name;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setName(String name) {
        this.name = name;
    }
}
